### ISSUE TITLE
Error trying to start

### ISSUE THREAD

**Issue by southbayjay** [crjaensch/PromptoLab#6]
Hey there! 

Trying to test out your app but I'm getting an error on start up.  I'm on windows 11 with python 3.10, maybe I'm over looking something?

`(venv) PS E:\PromptoLab> cd ..
(venv) PS E:\> python -m PromptoLab
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\PromptoLab\__main__.py", line 11, in <module>
    from main_window import MainWindow
  File "E:\PromptoLab\main_window.py", line 14, in <module>
    from evaluation_widget import EvaluationWidget
  File "E:\PromptoLab\evaluation_widget.py", line 20, in <module>
    from output_analyzer import (OutputAnalyzer, AnalysisResult, AnalysisError,
  File "E:\PromptoLab\output_analyzer.py", line 314
    {"".join(f"- {change}\n" for change in result.key_changes)}"""
                                                                  ^
SyntaxError: f-string expression part cannot include a backslash
(venv) PS E:\> python -m PromptoLab`

![image](https://github.com/user-attachments/assets/bb6f64b4-08d8-4eb7-8293-6816084ac7a7)

Thanks!
Jay

**Comment by southbayjay** [comment]
I opened it up in Windsurf and got it fixed. I was missing some packages and it made some changes to the code in the output_analyzer.py file. 

Is there supposed to be any data in it or is it supposed to be blank? 

Thanks!
Jay

**Comment by crjaensch** [comment]
Thanks, Jay for bringing this issue to my attention!
I looked into this and refactored the code to fix the issue. Privately, I don't have a Windows computer at hand to easily verify it. But I also asked WS to review my code changes w.r.t. Windows compatibility.

**Comment by crjaensch** [comment]
@southbayjay I would appreciate it if you could check whether my code updates fix the issue on your computer.
BTW, which packages were missing? I would like to update - if needed - the requirements.txt and the installation notes to ensure this is fixed for all who are trying to use the PromptoLab.

**Comment by southbayjay** [comment]
Let me see if I can export my chat from Windsurf. I don't where I can export the chat. There was quite a few packages it was telling me that I needed to install. The first was "PySide6", then it said I needed "scikit-learn",  then it was "nltk",  then it said to install "markdown", after that it finally ran. 

I'll do a git clone on the repo again and see if I can run it with the new fixes.

**Comment by crjaensch** [comment]
@southbayjay Ahh, it looks like you installed it without using the requirements.txt file. Please check the installation instructions in the README.md, where it states: python3 -m pip install -r requirements.txt

**Comment by southbayjay** [comment]
> @southbayjay Ahh, it looks like you installed it without using the requirements.txt file. Please check the installation instructions in the README.md, where it states: python3 -m pip install -r requirements.txt

It's possible I over looked it, that would make sense.

**Comment by southbayjay** [comment]
@crjaensch it installed without any errors this time.

**Comment by southbayjay** [comment]
Is there supposed to be any sample prompts included or no? I'm not seeing anything and honestly I'm not sure where to get started with it.

**Comment by crjaensch** [comment]
@southbayjay I am glad to hear this :-) Thanks, for checking it on your Windows computer. I appreciate your support on this.

**Comment by southbayjay** [comment]
Just noticed this error in the terminal.. 

`(venv) PS E:\> python -m PromptoLab
ERROR:llm_utils:Unexpected error getting LLM models: [WinError 2] The system cannot find the file specified
ERROR:llm_utils:Unexpected error getting LLM models: [WinError 2] The system cannot find the file specified`

**Comment by crjaensch** [comment]
I did not want to include sample prompts or test sets with the tool repo. 
But, I do plan to create a separate GitHub repo for useful prompts and sample test sets to get a head start with using PromptoLab.

**Comment by crjaensch** [comment]
See also: https://github.com/simonw/llm concerning the "llm" command line tool.

**Comment by southbayjay** [comment]
yes I did install the llm command

**Comment by southbayjay** [comment]
> See also: https://github.com/simonw/llm concerning the "llm" command line tool.

Ok great, thank you

**Comment by crjaensch** [comment]
PromptoLab is trying to create two directories in the same folder where you start the tool. One is called "prompts" and the other "test_sets". From the error message you displayed above I cannot tell what is causing the issue. May be an access rights issue trying to create the two directories I mentioned.

**Comment by crjaensch** [comment]
Or it cannot locate the "llm" command line tool, when it tries to obtain the models. Please check if you can execute "llm models" in a terminal window.

**Comment by southbayjay** [comment]
I have not setup anything yet for the llm tool, I'll do that now.

**Comment by crjaensch** [comment]
@southbayjay Hello Jay, can I close this issue? Or are you still having problems running PromptoLab?

**Comment by southbayjay** [comment]
Yes you can thank you
